-- Inserção de Paises no Banco
INSERT INTO PAIS (NOME, IBGE) VALUES ('Brasil', '1001');
INSERT INTO PAIS (NOME, IBGE) VALUES ('Argentina', '1002');
INSERT INTO PAIS (NOME, IBGE) VALUES ('Chile', '1003');
INSERT INTO PAIS (NOME, IBGE) VALUES ('Colômbia', '1004');
INSERT INTO PAIS (NOME, IBGE) VALUES ('Peru', '1005');
INSERT INTO PAIS (NOME, IBGE) VALUES ('Uruguai', '1006');
INSERT INTO PAIS (NOME, IBGE) VALUES ('Paraguai', '1007');
INSERT INTO PAIS (NOME, IBGE) VALUES ('Equador', '1008');
INSERT INTO PAIS (NOME, IBGE) VALUES ('Venezuela', '1009');
INSERT INTO PAIS (NOME, IBGE) VALUES ('Bolívia', '1010');

--  Inserção de Cidades no Banco
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Rio de Janeiro', '101', 1);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('São Paulo', '102', 1);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Belo Horizonte', '103', 1);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Salvador', '104', 1);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Recife', '105', 1);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Fortaleza', '106', 1);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Curitiba', '107', 1);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Porto Alegre', '108', 1);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Brasília', '109', 1);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Manaus', '110', 1);

INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Buenos Aires', '111', 2);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Córdoba', '112', 2);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Rosário', '113', 2);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Mendoza', '114', 2);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('San Miguel de Tucumán', '115', 2);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('La Plata', '116', 2);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Mar del Plata', '117', 2);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Salta', '118', 2);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Santa Fé', '119', 2);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('San Juan', '120', 2);

INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Santiago', '121', 3);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Valparaíso', '122', 3);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Viña del Mar', '123', 3);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Concepción', '124', 3);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('La Serena', '125', 3);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Antofagasta', '126', 3);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Temuco', '127', 3);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Valdivia', '128', 3);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Puerto Montt', '129', 3);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Iquique', '130', 3);

INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Bogotá', '131', 4);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Medellín', '132', 4);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Cali', '133', 4);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Barranquilla', '134', 4);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Cartagena', '135', 4);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Bucaramanga', '136', 4);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Cúcuta', '137', 4);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Pereira', '138', 4);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Santa Marta', '139', 4);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Ibagué', '140', 4);

INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Lima', '141', 5);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Arequipa', '142', 5);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Trujillo', '143', 5);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Chiclayo', '144', 5);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Piura', '145', 5);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Iquitos', '146', 5);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Cusco', '147', 5);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Chimbote', '148', 5);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Huancayo', '149', 5);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Tacna', '150', 5);

INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Montevidéu', '151', 6);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Salto', '152', 6);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Paysandú', '153', 6);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Rivera', '154', 6);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Maldonado', '155', 6);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Tacuarembó', '156', 6);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Artigas', '157', 6);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Las Piedras', '158', 6);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('San José de Mayo', '159', 6);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Rocha', '160', 6);

INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Assunção', '161', 7);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Ciudad del Este', '162', 7);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('San Lorenzo', '163', 7);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Luque', '164', 7);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Capiatá', '165', 7);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Lambaré', '166', 7);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Fernando de la Mora', '167', 7);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Encarnación', '168', 7);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Limpio', '169', 7);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Ñemby', '170', 7);

INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Quito', '171', 8);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Guayaquil', '172', 8);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Cuenca', '173', 8);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Santo Domingo', '174', 8);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Machala', '175', 8);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Portoviejo', '176', 8);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Ambato', '177', 8);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Manta', '178', 8);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Durán', '179', 8);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Loja', '180', 8);

INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Caracas', '181', 9);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Maracaibo', '182', 9);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Valência', '183', 9);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Maracay', '184', 9);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Barquisimeto', '185', 9);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Ciudad Guayana', '186', 9);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('San Cristóbal', '187', 9);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Barcelona', '188', 9);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Maturín', '189', 9);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Puerto la Cruz', '190', 9);

INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('La Paz', '191', 10);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Santa Cruz de la Sierra', '192', 10);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Cochabamba', '193', 10);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('El Alto', '194', 10);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Oruro', '195', 10);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Sucre', '196', 10);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Tarija', '197', 10);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Potosí', '198', 10);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Montero', '199', 10);
INSERT INTO CIDADE (NOME, IBGE, PAIS_ID) VALUES ('Trinidad', '200', 10);



